SELECT DISTINCT CO_DOMINIO, DS_DOMINIO FROM TE_TISS_DOMINIO WHERE FK_TISELE =
(SELECT PK_TISELE FROM TE_TISS_ELEMENTO WHERE CO_ELEMENTO = 'STATUS_SOLICITACAO') ORDER BY CO_DOMINIO

SELECT DISTINCT CO_DOMINIO, DS_DOMINIO  FROM TE_TISS_DOMINIO  WHERE FK_TISELE =
(SELECT PK_TISELE FROM TE_TISS_ELEMENTO WHERE CO_ELEMENTO = 'STATUS_CANCELAMENTO') ORDER BY CO_DOMINIO 

SELECT PK_STAINT, DESCRICAO  FROM TE_STATUS_INTAUTZ  WHERE PK_STAINT NOT IN (99)  ORDER BY PK_STAINT

SELECT COD_CAR FROM ESCARCAD WHERE SN_OPME = 'S'

--
SELECT CAB.PK_AUTCAB, CAB.FK_COD_UNI, CAB.FK_COD_CON, CAB.FK_COD_PLA, CAB.FK_STAINT,
DECODE(CAB.FK_STAINT,99,
  (DECODE(CAB.FK_TISDOM_STSOLIC,NULL,
         DECODE(CAB.FK_TISDOM_STCANC,NULL,
         (SELECT UPPER(DESCRICAO) FROM TE_STATUS_INTAUTZ WHERE PK_STAINT = CAB.FK_STAINT),
         (SELECT DOM.DS_DOMINIO FROM TE_TISS_DOMINIO DOM WHERE DOM.PK_TISDOM = CAB.FK_TISDOM_STCANC)),
  (SELECT DOM.DS_DOMINIO FROM TE_TISS_DOMINIO DOM WHERE DOM.PK_TISDOM = CAB.FK_TISDOM_STSOLIC))),
(SELECT UPPER(DESCRICAO) FROM TE_STATUS_INTAUTZ WHERE PK_STAINT = CAB.FK_STAINT)) AS RETORNO,
CAB.FK_TISDOM_STSOLIC,
CAB.FK_TISDOM_STCANC, CAB.FK_MSGAUT, CAB.CO_MATRICULA, CAB.DS_NOME_PACIENTE, CAB.TP_PACIENTE, CAB.FK_COD_PRO,
CAB.FK_COD_PRT, CAB.FK_COD_PAC, CAB.DH_SOLICITACAO, CAB.DT_PARA_PROCESSAR, CAB.NU_GUIA_PRESTADOR, CAB.NU_GUIA_OPERADORA,
CAB.NU_GUIA_PRINCIPAL, CAB.FK_MATRICULA, CAB.FK_MNEMON, CAB.DS_TARJAMAGNETICA, CAB.NU_SENHA_AUT, CAB.NU_SENHA_PRE_AUT,
CAB.QT_DIARIAS_SOLIC, CAB.QT_DIARIAS_AUTOR, CAB.DS_INTERFACE, CAB.ST_ENVIO, CAB.ST_PROCESSAMENTO, CAB.DH_INICIO_PROCESSO,
CAB.DH_FINAL_PROCESSO, CAB.FK_COD_GUIA, CAB.FK_COD_SEN, CAB.DT_AUTORIZACAO, CAB.DT_VALIDADE_SENHA, CAB.DT_VALIDADE_CART,
CAB.NU_CNS, CAB.DS_IND_CLINICA, CAB.DT_SUG_INTER, CAB.FK_CARATER_ATEND, CAB.FK_TIPO_INTER, CAB.FK_REG_INTER,
CAB.FK_IND_ACIDENTE, CAB.DS_COD_DOC_ORIGEM, CAB.FK_TP_ACOM_AUT, CAB.DS_JUST_OPERADORA, CAB.QT_DIA_ADIC_AUT,
MAU.DS_MENSAGEM,CON.FANTASIA, CASE CAB.TP_PACIENTE WHEN 'I' THEN 'Interno' WHEN 'E' THEN 'Externo' WHEN 'U'
THEN 'Urgencia'
WHEN 'A' THEN 'Ambulatorio' END MSG_PACIENTE, CAB.SN_LIB_PARA_PROC, CASE WHEN CAB.ST_ENVIO = '1' THEN 'Pendente de Envio'
  WHEN CAB.ST_ENVIO = '2' THEN 'Enviado' WHEN CAB.ST_ENVIO = '3' THEN 'Finalizado' END MSG_ENVIO, CASE MAU.DS_MENSAGEM
    WHEN 'Solicitacao de Prorrogacao TISS' THEN 'P' END AS PRORROG, (SELECT DISTINCT RSVCAD.COD_RSV  FROM  RCRSVCAD RSVCAD
      INNER JOIN RCCIRRSV RSVITEM ON RSVCAD.COD_RSV = RSVITEM.COD_RSV WHERE RSVCAD.FK_AUTCAB = CAB.PK_AUTCAB  )AS COD_RSV,
      CAB.FK_STAINT, (SELECT MAX('S')    FROM TB_ANEXO_GUIA ANX   WHERE ANX.FK_AUTCAB = CAB.PK_AUTCAB) TEM_ANEXO,
      (SELECT MAX('S')    FROM TB_ANEXO_GUIA ANX   WHERE ANX.FK_AUTCAB = CAB.PK_AUTCAB     AND TP_ANEXO = 'O') TEM_OPME,
      (SELECT MAX('S')    FROM TB_ANEXO_GUIA ANX   WHERE ANX.FK_AUTCAB = CAB.PK_AUTCAB     AND TP_ANEXO = 'Q') TEM_QUIMIO,
       (SELECT MAX('S')    FROM TB_ANEXO_GUIA ANX   WHERE ANX.FK_AUTCAB = CAB.PK_AUTCAB     AND TP_ANEXO = 'R') TEM_RADIO
       FROM TB_AUTORIZ_CABEC CAB,  TE_MSGAUTORIZADOR MAU,  FACONCAD CON WHERE  CAB.FK_MSGAUT = MAU.PK_MSGAUT
       AND CAB.FK_COD_CON = CON.COD_CON AND CAB.FK_MSGAUT <> 9 and cab.fk_cod_uni = '0001' and cab.fk_cod_con = '014'
       and cab.st_envio in ('1', '2', '3')and cab.dh_solicitacao >= to_date('01/08/2015','dd/mm/yyyy')
       and cab.dh_solicitacao <= to_date('05/08/2015 23:59:59','dd/mm/yyyy HH24:MI:SS')  AND PK_AUTCAB NOT IN
       (SELECT FK_AUTCAB FROM TB_AUTORIZ_ITEM INNER JOIN RCCIRRSV ON (PK_AUTITE = FK_AUTITE)) 
 ORDER BY PK_AUTCAB, DH_SOLICITACAO
 
 --
 SELECT RAC.PK_RTAUTC, RAC.FK_AUTCAB, RAC.FK_STAINT, DECODE(RAC.FK_STAINT,99,(DECODE(RAC.FK_TISDOM_STSOLIC,NULL,
DECODE(RAC.FK_TISDOM_STCANC,NULL,(SELECT UPPER(DESCRICAO) FROM TE_STATUS_INTAUTZ WHERE PK_STAINT = RAC.FK_STAINT),
(SELECT DOM.DS_DOMINIO FROM TE_TISS_DOMINIO DOM WHERE DOM.PK_TISDOM = RAC.FK_TISDOM_STCANC)),
(SELECT DOM.DS_DOMINIO FROM TE_TISS_DOMINIO DOM WHERE DOM.PK_TISDOM = RAC.FK_TISDOM_STSOLIC))),(SELECT UPPER(DESCRICAO)
FROM TE_STATUS_INTAUTZ WHERE PK_STAINT = RAC.FK_STAINT)) AS RETORNO, RAC.FK_TISDOM_STSOLIC, RAC.FK_TISDOM_STCANC,
RAC.TP_CONTATO, RAC.DH_RETORNO, RAC.DS_OBSERVACAO, RAC.REF_ARQ, 0 PK_RTAUTI, CASE WHEN RAC.REF_ARQ IS NULL THEN 0 ELSE 1
END AS REF_ARQ_ICONE FROM TB_RETAUT_CABEC RAC WHERE RAC.FK_AUTCAB = 4163  ORDER BY DH_RETORNO
