SELECT CAB.FK_COD_PAC, CAB.DS_NOME_PACIENTE, DECODE(CAB.FK_STAINT,99,
         (DECODE(CAB.FK_TISDOM_STSOLIC,NULL,
         DECODE(CAB.FK_TISDOM_STCANC,NULL,
         (SELECT UPPER(DESCRICAO) FROM TE_STATUS_INTAUTZ WHERE PK_STAINT = CAB.FK_STAINT),
         (SELECT DOM.DS_DOMINIO FROM TE_TISS_DOMINIO DOM WHERE DOM.PK_TISDOM = CAB.FK_TISDOM_STCANC)),
         (SELECT DOM.DS_DOMINIO FROM TE_TISS_DOMINIO DOM WHERE DOM.PK_TISDOM = CAB.FK_TISDOM_STSOLIC))),
         (SELECT UPPER(DESCRICAO) FROM TE_STATUS_INTAUTZ WHERE PK_STAINT = CAB.FK_STAINT)) AS RETORNO,
a.apelido, CAB.DH_INICIO_PROCESSO, CAB.DH_FINAL_PROCESSO, CAB.NU_SENHA_AUT, CAB.NU_SENHA_PRE_AUT, CON.FANTASIA

       FROM TB_AUTORIZ_CABEC CAB,  TE_MSGAUTORIZADOR MAU, FACONCAD CON, fausucad a

       WHERE  CAB.FK_MSGAUT = MAU.PK_MSGAUT and cab.fk_matricula = a.matricula
       AND CAB.FK_COD_CON = CON.COD_CON AND CAB.FK_MSGAUT <> 9 and cab.fk_cod_uni = '0001'
       --and cab.fk_cod_con = '014'
       and cab.st_envio in ('1', '2', '3')
       and cab.dh_solicitacao >= to_date('01/08/2015','dd/mm/yyyy')
       and cab.dh_solicitacao <= to_date('05/08/2015 23:59:59','dd/mm/yyyy HH24:MI:SS')
       AND PK_AUTCAB NOT IN
       (SELECT FK_AUTCAB FROM TB_AUTORIZ_ITEM INNER JOIN RCCIRRSV ON (PK_AUTITE = FK_AUTITE)) 
 ORDER BY PK_AUTCAB, DH_SOLICITACAO
