select distinct round((select count(*) from CTRL_HOR_PROF_CC CT, RCRSVCAD RS where CT.COD_RSV=RS.COD_RSV
and RS.DATA_INICIAL>='01/07/2017' AND RS.DATA_INICIAL<='01/07/2017'
and ROUND(To_Char(CT.DATA_INI_ANEST - RS.HORA_INICIAL)*1*24*60) >20)/
(select count(*) from CTRL_HOR_PROF_CC CT, RCRSVCAD RS where CT.COD_RSV=RS.COD_RSV
and RS.DATA_INICIAL>='01/07/2017' AND RS.DATA_INICIAL<='01/07/2017')*100,2)
from CTRL_HOR_PROF_CC CT, RCRSVCAD RS where CT.COD_RSV=RS.COD_RSV
