SELECT distinct blciru_realizada.COD_PAC, BLCIRU_REALIZADA.CD_CIRU_REALIZADA, faprtcad.nome_pac
FROM BLCIRU_REALIZADA, BLSTAT_CIRU_REZD, BLCIRU_STATUS, BLPROC_CIRURGICO, FAPROCAD, BLEQPE_PROC_CIRU, fapaccad, faprtcad
WHERE  BLCIRU_REALIZADA.CD_CIRU_REALIZADA = BLSTAT_CIRU_REZD.CD_CIRU_REALIZADA
AND  BLSTAT_CIRU_REZD.CD_CIRU_STATUS      = BLCIRU_STATUS.CD_CIRU_STATUS
AND  BLCIRU_REALIZADA.CD_CIRU_REALIZADA   = BLPROC_CIRURGICO.CD_CIRU_REALIZADA
AND  BLPROC_CIRURGICO.CD_CIRU_REALIZADA   = BLEQPE_PROC_CIRU.CD_CIRU_REALIZADA
AND  BLEQPE_PROC_CIRU.CD_PROFISSIONAL     = FAPROCAD.COD_PRO
and blciru_realizada.cod_pac = fapaccad.cod_pac
and fapaccad.cod_prt = faprtcad.cod_prt
--AND  BLEQPE_PROC_CIRU.COD_ATO IN ('01')
/*AND  BLCIRU_STATUS.CD_CIRU_STATUS in ('F','E','R')*/
AND BLPROC_CIRURGICO.DATA_HORA_INI >= '01/04/2013'
AND BLPROC_CIRURGICO.DATA_HORA_FIM <= '01/05/2013'
--and faprocad.cod_pro = '000788'
GROUP BY NOME_PRO, faprocad.COD_PRO, blciru_realizada.COD_PAC, BLCIRU_REALIZADA.CD_CIRU_REALIZADA, fapaccad.data_ent, faprtcad.nome_pac
select * from blproc_cirurgico where BLPROC_CIRURGICO.DATA_HORA_INI >= '01/04/2013'
AND BLPROC_CIRURGICO.DATA_HORA_FIM <= '01/05/2013'
