SELECT FAPRDCAD.DESCRICAO, FAPROCAD.COD_PRO, FAPROCAD.NOME_PRO, FAESPCAD.DESCRICAO DESCRICAO_2, BLCIRU_REALIZADA.COD_PAC, 
       COUNT(*) COUNT_2, BLPROC_CIRURGICO.DATA_HORA_INI
FROM BLCIRU_REALIZADA BLCIRU_REALIZADA, BLSTAT_CIRU_REZD BLSTAT_CIRU_REZD, BLCIRU_STATUS BLCIRU_STATUS,
     BLPROC_CIRURGICO BLPROC_CIRURGICO, FAPRDCAD FAPRDCAD, BLEQPE_PROC_CIRU BLEQPE_PROC_CIRU, FAPROCAD FAPROCAD, FAESPPRO FAESPPRO,
     FAESPCAD FAESPCAD
WHERE (BLSTAT_CIRU_REZD.CD_CIRU_REALIZADA = BLCIRU_REALIZADA.CD_CIRU_REALIZADA) AND 
      (BLCIRU_STATUS.CD_CIRU_STATUS = BLSTAT_CIRU_REZD.CD_CIRU_STATUS) AND 
      (BLPROC_CIRURGICO.CD_CIRU_REALIZADA = BLCIRU_REALIZADA.CD_CIRU_REALIZADA) AND 
      (FAPRDCAD.CODIGO = BLPROC_CIRURGICO.CD_PROC_CIRURGICO) AND 
      (BLEQPE_PROC_CIRU.CD_PROC_CIRURGICO = BLPROC_CIRURGICO.CD_PROC_CIRURGICO) AND
      (BLEQPE_PROC_CIRU.CD_CIRU_REALIZADA = BLPROC_CIRURGICO.CD_CIRU_REALIZADA) AND
      (BLEQPE_PROC_CIRU.REGIAO = BLPROC_CIRURGICO.REGIAO) AND (FAPROCAD.COD_PRO = BLEQPE_PROC_CIRU.CD_PROFISSIONAL)
       AND (FAESPPRO.COD_PRO = FAPROCAD.COD_PRO) AND (FAESPCAD.COD_ESP = FAESPPRO.COD_ESP)
       AND (( BLEQPE_PROC_CIRU.COD_ATO = '01') AND ( BLCIRU_STATUS.CD_CIRU_STATUS = 'E') AND ( FAESPPRO.SN_PRINCIPAL = 'S')
       AND BLPROC_CIRURGICO.DATA_HORA_INI between '01/01/2017' and '31/05/2017')
GROUP BY FAPRDCAD.DESCRICAO, FAPROCAD.COD_PRO, FAPROCAD.NOME_PRO, FAESPCAD.DESCRICAO, BLCIRU_REALIZADA.COD_PAC, 
         BLPROC_CIRURGICO.DATA_HORA_INI
ORDER BY FAPROCAD.COD_PRO, FAPRDCAD.DESCRICAO
