SELECT faprdcad.descricao,faespcad.descricao, count(faprdcad.descricao)
FROM BLCIRU_REALIZADA, BLSTAT_CIRU_REZD, BLCIRU_STATUS, BLPROC_CIRURGICO, FAPRDCAD, FAPROCAD, BLEQPE_PROC_CIRU,
faespcad, faesppro WHERE  BLCIRU_REALIZADA.CD_CIRU_REALIZADA = BLSTAT_CIRU_REZD.CD_CIRU_REALIZADA
AND  BLSTAT_CIRU_REZD.CD_CIRU_STATUS      = BLCIRU_STATUS.CD_CIRU_STATUS
AND  BLCIRU_REALIZADA.CD_CIRU_REALIZADA   = BLPROC_CIRURGICO.CD_CIRU_REALIZADA
AND  BLPROC_CIRURGICO.CD_PROC_CIRURGICO   = FAPRDCAD.CODIGO
AND  BLPROC_CIRURGICO.CD_PROC_CIRURGICO   = BLEQPE_PROC_CIRU.CD_PROC_CIRURGICO
AND  BLPROC_CIRURGICO.CD_CIRU_REALIZADA   = BLEQPE_PROC_CIRU.CD_CIRU_REALIZADA
AND  BLPROC_CIRURGICO.REGIAO = BLEQPE_PROC_CIRU.REGIAO AND BLEQPE_PROC_CIRU.CD_PROFISSIONAL = FAPROCAD.COD_PRO
and faprocad.cod_pro = faesppro.cod_pro and faespcad.cod_esp = faesppro.cod_esp
and faesppro.sn_principal = 'S' AND  BLEQPE_PROC_CIRU.COD_ATO IN ('01') AND  BLCIRU_STATUS.CD_CIRU_STATUS = 'E'
AND BLPROC_CIRURGICO.DATA_HORA_INI >= '01/03/2016' AND BLPROC_CIRURGICO.DATA_HORA_INI <= '31/03/2016'
--and faprocad.cod_pro = '000933'
group by faprdcad.descricao, faespcad.descricao
ORDER BY count(faprdcad.descricao) desc, faprdcad.descricao
