SELECT ITENS_PED_PROCED.NUM_PEDIDO,ITENS_PED_PROCED.COD_PRD,ITENS_PED_PROCED.REGIAO,ITENS_PED_PROCED.COD_UNI,ITENS_PED_PROCED.COD_SALA,
ITENS_PED_PROCED.URGENTE,ITENS_PED_PROCED.TIPO,ITENS_PED_PROCED.SENHA_AUT,RPAD(TO_CHAR(ITENS_PED_PROCED.MATRICULA),40,' ') MATRICULA,
ITENS_PED_PROCED.COD_GLOSA,ITENS_PED_PROCED.DESCR_GLOSA,ITENS_PED_PROCED.TIPO_COMANDA,ITENS_PED_PROCED.COMANDA,ITENS_PED_PROCED.COD_PRO,
ITENS_PED_PROCED.CONFIRMADO,ITENS_PED_PROCED.COD_PRO_SOLIC,ITENS_PED_PROCED.DSC_OBSERVACAO,
RPAD(TO_CHAR(ITENS_PED_PROCED.FK_AUTITE),40,' ') FK_AUTITE,
RPAD(TO_CHAR(PEDIDOS_PROCED.DATA_HORA,'DD/MM/YYYY hh24:mi'),129,' ') DATA_HORA,PEDIDOS_PROCED.DATA_HORA DATA_HORA_ORD, FAPACCAD.LEITO,
PEDIDOS_PROCED.COD_PAC,PEDIDOS_PROCED.COD_PRO AS SOLIC, PEDIDOS_PROCED.DSC_OBSERVACAO, (SELECT NOME_UNI FROM AMUNICAD
WHERE COD_UNI = ITENS_PED_PROCED.COD_UNI) NOME_UNIC, (SELECT NOME_PRO FROM FAPROCAD WHERE COD_PRO = ITENS_PED_PROCED.COD_PRO) EXECUTANTEC,
(SELECT NOME_PRO FROM FAPROCAD WHERE COD_PRO = PEDIDOS_PROCED.COD_PRO) SOLICITANTE, (SELECT DESCRICAO FROM IMSALCAD
WHERE COD_UNI = ITENS_PED_PROCED.COD_UNI AND COD_SALA = ITENS_PED_PROCED.COD_SALA) NOME_SALAC, FAPRDCAD.DESCRICAO DESCRICAOC,
FAPRDCAD.TIPO_PRD, FAPRDCAD.COD_GRU, FATIPCAD.PRE_CLASS, FAPACCAD.COD_UNI COD_UNI_PAC, FAPACCAD.TIPO_PAC, FAPACCAD.COD_CON,
FAPACCAD.COD_PLA, FAPRTCAD.SEXO, FAPRTCAD.NOME_PAC, FAPACCAD.MATRICULA MATRIC, (SELECT MIN(COD_KIT) FROM LBEXAKIT
WHERE CODIGO = ITENS_PED_PROCED.COD_PRD) COD_KIT, RPAD(TO_CHAR(FAPRTCAD.NASCIMENTO,'DD/MM/YYYY'),129,' ')  NASCIMENTO,
(SELECT FAAPTCAD.COD_SET FROM FALEICAD, FAAPTCAD WHERE FALEICAD.LEITO = FAPACCAD.LEITO AND FAAPTCAD.COD_APT = FALEICAD.COD_APT) COD_SET_LEITO,
 (SELECT RPAD(TO_CHAR(TI.FK_AUTCAB),40,' ')  FROM TB_AUTORIZ_ITEM TI  WHERE TI.PK_AUTITE = ITENS_PED_PROCED.FK_AUTITE) FK_AUTCAB,
 (SELECT RPAD(TO_CHAR(TI.FK_RETATZ),40,' ')  FROM TB_AUTORIZ_ITEM TI  WHERE TI.PK_AUTITE = ITENS_PED_PROCED.FK_AUTITE) FK_RETATZ,
 (SELECT TR.DS_RETORNO_AUT  FROM TE_RETORNO_AUTRZD TR, TB_AUTORIZ_ITEM TI  WHERE TI.PK_AUTITE = ITENS_PED_PROCED.FK_AUTITE 
 AND TR.PK_RETATZ = TI.FK_RETATZ) DS_DESC_AUT, (SELECT TC.NU_SENHA_PRE_AUT  FROM TB_AUTORIZ_ITEM TI, TB_AUTORIZ_CABEC TC
 WHERE TI.FK_AUTCAB = TC.PK_AUTCAB  AND TI.PK_AUTITE = ITENS_PED_PROCED.FK_AUTITE) NU_SENHA_PRE_AUT
 FROM ITENS_PED_PROCED,PEDIDOS_PROCED, FAPACCAD, FAPRTCAD, FAPRDCAD, FATIPCAD WHERE ITENS_PED_PROCED.NUM_PEDIDO = PEDIDOS_PROCED.NUM_PEDIDO
 AND ITENS_PED_PROCED.COD_PRD = FAPRDCAD.CODIGO AND FAPRDCAD.TIPO_PRD = FATIPCAD.TIPO_PRD AND PEDIDOS_PROCED.CONSULTA = 'N'
 AND PEDIDOS_PROCED.COD_PAC = FAPACCAD.COD_PAC AND FAPRTCAD.COD_PRT = FAPACCAD.COD_PRT  AND PEDIDOS_PROCED.COD_PAC = '3286728'
 AND ITENS_PED_PROCED.COD_PRD IN (SELECT CODIGO FROM FAPRDCAD WHERE CODIGO = ITENS_PED_PROCED.COD_PRD AND COD_BANCADA IS NULL) 
 AND FAPACCAD.COD_UNI IN ('0001')  ORDER BY ITENS_PED_PROCED.COD_UNI, ITENS_PED_PROCED.COD_SALA, DATA_HORA_ORD
