SELECT P.CODIGO, P.DESCRICAO, S.COD_SET, S.DESCRICAO, V.LOTE, V.VALIDADE, F.NOME AS FABRICANTE,
V.COD_BARRA_INT, NVL(E.EST_ATU,0) EST_ATU, NVL(E.EST_BLOQ,0) EST_BLOQ, (NVL(E.EST_ATU,0) - NVL(E.EST_BLOQ,0) - NVL(E.EST_KIT,0)) EST_DISP,
V.FK_DOCUMENTO FK_DOCUMENTO,
DECODE(Trim(V.FK_DOCUMENTO),NULL,'Não','Sim') AS MAT_CONSIGNADO

FROM ESESTMOV M,  ESMOVCAD C, ESLOTE_VALIDADE V, ESESTCAD E, FASETCAD S, ESFABRICANTE F,ESPECIE_NOTA EN, TE_TPESP_NF_CONSIG TP,
FAPRDCAD P

WHERE  S.COD_SET = E.COD_SET   AND E.COD_SET = M.COD_SET   AND E.COD_PRD = M.COD_PRD
AND E.COD_PRD = P.CODIGO
AND (E.EST_ATU > 0 OR E.EST_KIT > 0)   AND E.COD_BARRA_INT = V.COD_BARRA_INT   AND V.COD_FABRICANTE = F.COD_FABRICANTE
AND TP.PK_ESNFCG(+) = EN.FK_ESNFCG   AND EN.COD_ESPECIE(+) = C.FK_COD_ESPECIE   AND C.TIPO_DOCUMENTO(+) = V.FK_TIPO_DOCUMENTO
AND C.DOCUMENTO(+) = V.FK_DOCUMENTO   AND C.NOTA(+) = V.FK_NOTA
and v.fk_documento is not null ORDER BY S.COD_SET, V.COD_BARRA_INT 
