SELECT distinct FAPACCAD.DATA_ENT, FAPACCAD.COD_PAC, FAPROCAD.NOME_PRO, FAPRTCAD.NOME_PAC, FAMOVDESTINO.VALOR, FACONCAD.FANTASIA, 
       FAPRDCAD.DESCRICAO, to_char(famovcad.hora_mov,'HH24:MI') to_char_fapaccad_h
FROM FAPACCAD FAPACCAD, FAPROCAD FAPROCAD, FAPRTCAD FAPRTCAD, FAMOVCAD FAMOVCAD, FAMOVPRD FAMOVPRD, FAMOVDESTINO FAMOVDESTINO
     , FACONCAD FACONCAD, FAPRDCAD FAPRDCAD, FAESPPRO FAESPPRO, FAESPCAD FAESPCAD
WHERE (FAPROCAD.COD_PRO = FAMOVPRD.COD_PRO) AND (FAPRTCAD.COD_PRT = FAPACCAD.COD_PRT) AND (FAMOVCAD.COD_PAC = FAPACCAD.COD_PAC) AND 
      (FAMOVPRD.TIPO_COMANDA = FAMOVCAD.TIPO_COMANDA)AND (FAMOVPRD.COMANDA = FAMOVCAD.COMANDA)
       AND (FAMOVDESTINO.SEQUENCIAL = FAMOVPRD.SEQUENCIAL) AND (FACONCAD.COD_CON = FAPACCAD.COD_CON)
       AND (FAPRDCAD.CODIGO = FAMOVPRD.CODIGO) AND (FAESPPRO.COD_PRO = FAPROCAD.COD_PRO)
       AND (FAESPCAD.COD_ESP = FAESPPRO.COD_ESP) --AND (( FAPRDCAD.TIPO_PRD = 'CON' )
--       AND ( FAPACCAD.TIPO_PAC = 'A' )
       AND ( famovcad.data_mov BETWEEN TO_DATE('2015/09/01','YYYY/MM/DD') AND TO_DATE('2015/09/30','YYYY/MM/DD') )
       AND (    to_char(famovcad.hora_mov,'HH24:MI') between '13:00' and '23:59' ) AND ( FAMOVPRD.COD_PRO = '006671' )
       and faprdcad.codigo in ('009200','052022','000067','052048','052049','000002')
ORDER BY FAPACCAD.DATA_ENT
