SELECT FATIPCAD.DESCRICAO DESCRICAO_2, 
       FAPRDCAD.DESCRICAO DESCRICAO_3, 
       SUM(ESMOVITE.QUANT) SUM_ESMOVITE_QUANT
FROM ESMOVCAD ESMOVCAD, ESMOVITE ESMOVITE
     , FAPRDCAD FAPRDCAD, FATIPCAD FATIPCAD
WHERE 
      (ESMOVITE.TIPO_DOCUMENTO = ESMOVCAD.TIPO_DOCUMENTO)
       AND (ESMOVITE.DOCUMENTO = ESMOVCAD.DOCUMENTO)
       AND (FAPRDCAD.CODIGO = ESMOVITE.COD_PRD)
       AND (FATIPCAD.TIPO_PRD = FAPRDCAD.TIPO_PRD)
       AND 
      ( ESMOVCAD.DATA_MOV BETWEEN TO_DATE('2017/01/01','YYYY/MM/DD') AND TO_DATE('2017/01/31','YYYY/MM/DD') )
       AND ( ESMOVCAD.TIPO_DOCUMENTO = 'COM' )--REQ/COM
       AND ( FATIPCAD.NATUREZA IS NULL  )
       AND ( FAPRDCAD.TIPO_PRD = 'MED' )
--       AND ( ESMOVCAD.CRED_DEB = 'C' )--Quando for REQ
GROUP BY FATIPCAD.DESCRICAO, FAPRDCAD.DESCRICAO
ORDER BY FAPRDCAD.DESCRICAO
