SELECT to_char(FAPACCAD.DATA_ENT,'MM') mes, FAESPCAD.COD_ESP, FAESPCAD.DESCRICAO, COUNT(*) COUNT_2
FROM FAPACCAD FAPACCAD, FAESPCAD FAESPCAD
WHERE (FAESPCAD.COD_ESP = FAPACCAD.COD_ESP) AND (
( FAPACCAD.DATA_ENT BETWEEN '01/01/2013' AND '31/08/2013' )
--      ( FAPACCAD.DATA_ENT BETWEEN &data_ent AND &data_ent )
       AND ( FAPACCAD.TIPO_PAC = 'A' ))
GROUP BY to_char(FAPACCAD.DATA_ENT,'MM'), FAESPCAD.COD_ESP, FAESPCAD.DESCRICAO
ORDER BY 3 DESC, 1
