SELECT faprdcad.tipo_prd, CODIGO_BARRAS.COD_PRODUTO, faprdcad.descricao, ESFABRICANTE.NOME, CODIGO_BARRAS.COD_BARRAS, CODIGO_BARRAS.QTD_EMBALAGEM,
CODIGO_BARRAS.COD_TIPO, CODIGO_BARRAS.COD_FABRICANTE FROM FAPRDCAD, CODIGO_BARRAS, ESFABRICANTE WHERE FAPRDCAD.CODIGO = FAPRDCAD.CODIGO
AND CODIGO_BARRAS.COD_PRODUTO = FAPRDCAD.CODIGO --AND CODIGO_BARRAS.COD_PRODUTO ='118990'
AND CODIGO_BARRAS.COD_FABRICANTE = ESFABRICANTE.COD_FABRICANTE(+)
--and faprdcad.tipo_prd in ('DES','MAT','ESP','FIO','OPM')
--and faprdcad.tipo_prd in ('FNU','MED')
and faprdcad.tipo_prd not in ('DES','MAT','ESP','FIO','OPM','FNU','MED','PRO','KIT')
order by 1,3
