SELECT FAPACCAD.COD_PRO, FAPROCAD.NOME_PRO, fatipcad.descricao, count(fatipcad.descricao)
FROM FAPACCAD FAPACCAD, FAPROCAD FAPROCAD
     , IMMOVCAD IMMOVCAD, IMMOVPRD IMMOVPRD
     , FAPRDCAD FAPRDCAD, FATIPCAD FATIPCAD
WHERE (FAPROCAD.COD_PRO = FAPACCAD.COD_PRO)
       AND (IMMOVCAD.COD_PAC = FAPACCAD.COD_PAC)
       AND (IMMOVPRD.COMANDA = IMMOVCAD.COMANDA)
       AND (IMMOVPRD.TIPO_COMANDA = IMMOVCAD.TIPO_COMANDA)
       AND (FAPRDCAD.CODIGO = IMMOVPRD.COD_PRD)
       AND (FATIPCAD.TIPO_PRD = FAPRDCAD.TIPO_PRD)
       and faprdcad.tipo_prd in (select tipo_prd from fatipcad where pre_class = 'EXA')
       and faprdcad.tipo_prd  not in ('EXA','LAB')
       AND (
      ( FAPACCAD.DATA_ENT BETWEEN TO_DATE('2012/05/01','YYYY/MM/DD') AND TO_DATE('2012/05/31','YYYY/MM/DD') )
       --AND ( FAPACCAD.COD_PRO_SA IN ('003176','000667') )
       AND ( IMMOVCAD.COD_UNI = '0001' ))
       --AND ( FAPACCAD.TIPO_PAC = 'U' ))
GROUP BY FAPACCAD.COD_PRO, FAPROCAD.NOME_PRO, fatipcad.descricao
ORDER BY FAPROCAD.NOME_PRO
