SELECT sum(SUM(FAMOVPRD.QUANT * DECODE(REQ_DEV,'R',1,-1) /
(SELECT COUNT(*) FROM FAMOVDESTINO WHERE SEQUENCIAL = FAMOVPRD.SEQUENCIAL 
AND FAMOVDESTINO.DESTINO IN ('H','C','P')))) AS QTD_PER
FROM FAMOVDESTINO, FATIPCAD, FASETCAD,FAPRDCAD, FAPACCAD, FAMOVCAD, FAMOVPRD, FAPRTCAD
WHERE FAMOVCAD.DATA_MOV >= '01/07/2017'
AND FAMOVCAD.DATA_MOV <= '31/07/2017'
AND FAMOVDESTINO.DESTINO IN ('H','C','P') AND FAPRDCAD.TIPO_PRD = 'RAD'
AND FAPRDCAD.COD_GRU NOT IN ('DENS', 'MAMO') AND fapaccad.cod_uni IN ('0001')
AND FAMOVDESTINO.COD_UNI_COBRANCA IN ('0001') AND FAMOVDESTINO.SEQUENCIAL = FAMOVPRD.SEQUENCIAL 
AND FAMOVPRD.TIPO_COMANDA = FAMOVCAD.TIPO_COMANDA AND FAMOVPRD.COMANDA = FAMOVCAD.COMANDA AND FAMOVPRD.CODIGO  = FAPRDCAD.CODIGO
AND FAPACCAD.COD_PRT = FAPRTCAD.COD_PRT AND FAMOVCAD.COD_PAC = FAPACCAD.COD_PAC AND FAPRDCAD.TIPO_PRD = FATIPCAD.TIPO_PRD
AND FAMOVCAD.SET_ORI  = FASETCAD.COD_SET
and fapaccad.tipo_pac = 'U'
GROUP BY FAPRDCAD.CODIGO,FAPRDCAD.TIPO_PRD , FAPRDCAD.DESCRICAO
