SELECT ITEM_SOL_EXA.COD_PAC, fapaccad.nome_segu, ITEM_SOL_EXA.CODIGO, faprdcad.tipo_prd, FAPRDCAD.DESCRICAO, ITEM_SOL_EXA.DAT_SOLICITACAO,
       ITEM_SOL_EXA.REGIAO, SOL_EXAME.COD_PRO_SOLIC, faprocad.nome_pro, SOL_EXAME.DATA_HORA_PED_EXA, FAPRDCAD.COD_AMB, FAPRDCAD.COD_CBHPM
  FROM ITEM_SOL_EXA
  JOIN FAPACCAD ON ITEM_SOL_EXA.COD_PAC = FAPACCAD.COD_PAC
  JOIN FAPRDCAD ON FAPRDCAD.CODIGO = ITEM_SOL_EXA.CODIGO
  INNER JOIN SOL_EXAME ON ITEM_SOL_EXA.COD_PAC = SOL_EXAME.COD_PAC 
         AND ITEM_SOL_EXA.DAT_SOLICITACAO = SOL_EXAME.DAT_SOLICITACAO
         inner join faprocad on sol_exame.cod_pro_solic = faprocad.cod_pro 
  LEFT JOIN LBMATCAD ON ITEM_SOL_EXA.COD_MAT_COLETA = LBMATCAD.COD_MAT_COLETA
  LEFT JOIN URCIDCAD ON ITEM_SOL_EXA.FK_UR_CID      = URCIDCAD.PK_UR_CID
  inner join fapaccad pac on SOL_EXAME.COD_PAC = pac.cod_pac--
  WHERE /*pac.tipo_pac = 'U' AND */ITEM_SOL_EXA.DAT_SOLICITACAO between TO_DATE('01/10/2017 00:00','dd%mm%yyyy hh24:mi')
  and TO_DATE('31/10/2017 23:59','dd%mm%yyyy hh24:mi')
  and faprdcad.tipo_prd in ('TOM')
   
  order by ITEM_SOL_EXA.DAT_SOLICITACAO
