SELECT FAPROCAD.NOME_PRO, FAPRDCAD.TIPO_PRD, 
       FATIPCAD.DESCRICAO, 
       IMMOVCAD.COD_PRO_SOLIC, COUNT(*) COUNT_2
FROM FAPACCAD FAPACCAD, FAPROCAD FAPROCAD
     , IMMOVCAD IMMOVCAD, IMMOVPRD IMMOVPRD
     , FAPRDCAD FAPRDCAD, FATIPCAD FATIPCAD
WHERE (FAPROCAD.COD_PRO = IMMOVCAD.COD_PRO_SOLIC)
       AND (IMMOVCAD.COD_PAC = FAPACCAD.COD_PAC)
       AND (IMMOVPRD.COMANDA = IMMOVCAD.COMANDA)
       AND (IMMOVPRD.TIPO_COMANDA = IMMOVCAD.TIPO_COMANDA)
       AND (FAPRDCAD.CODIGO = IMMOVPRD.COD_PRD)
       AND (FATIPCAD.TIPO_PRD = FAPRDCAD.TIPO_PRD)
       AND (
      ( FAPACCAD.DATA_ENT BETWEEN TO_DATE('2013/07/01','YYYY/MM/DD') AND TO_DATE('2013/12/31','YYYY/MM/DD') )
       AND ( IMMOVCAD.COD_UNI = '0001' )
       AND ( FAPACCAD.TIPO_PAC IN ('U','E','I','A') ))
       and faprocad.cod_pro = '000122'
       and faprdcad.tipo_prd <> 'CON'
GROUP BY IMMOVCAD.COD_PRO_SOLIC, 
         FAPROCAD.NOME_PRO, FAPRDCAD.TIPO_PRD, 
         FATIPCAD.DESCRICAO
union all
SELECT FAPROCAD.NOME_PRO, FAPRDCAD.TIPO_PRD, FATIPCAD.DESCRICAO, lbMOVCAD.Cod_Pro_Solic, COUNT(*) COUNT_2
FROM FAPACCAD FAPACCAD, FAPROCAD FAPROCAD, lbMOVCAD lbMOVCAD, lbMOVPRD lbMOVPRD
     , FAPRDCAD FAPRDCAD, FATIPCAD FATIPCAD
WHERE (FAPROCAD.COD_PRO = lbMOVCAD.COD_PRO_SOLIC)
       AND (lbMOVCAD.COD_PAC = FAPACCAD.COD_PAC)
       AND (lbMOVPRD.COMANDA = lbMOVCAD.COMANDA)
       AND (lbMOVPRD.TIPO_COMANDA = lbMOVCAD.TIPO_COMANDA)
       AND (FAPRDCAD.CODIGO = lbMOVPRD.CODigo)
       AND (FATIPCAD.TIPO_PRD = FAPRDCAD.TIPO_PRD)
       AND (
      ( FAPACCAD.DATA_ENT BETWEEN TO_DATE('2013/07/01','YYYY/MM/DD') AND TO_DATE('2013/12/31','YYYY/MM/DD') )
       AND ( FAPACCAD.TIPO_PAC IN ('U','E','I','A') ))
       and faprocad.cod_pro = '000122'
       and faprdcad.tipo_prd <> 'CON'
GROUP BY lbmovcad.cod_pro_solic, 
         FAPROCAD.NOME_PRO, FAPRDCAD.TIPO_PRD, 
         FATIPCAD.DESCRICAO
ORDER BY 3
