SELECT '                                   ' AS CDESCPRD,
COD_CON,COD_PLA,COD_PRD,' ' AS CEXIGESENINT,' ' AS CEXIGEGUIINT,' ' AS CEXIGEAUTINT,' ' AS CEXIGESENEXT,' ' AS CEXIGEGUIEXT,
' ' AS CEXIGEAUTEXT,' ' AS CEXIGESENURG,' ' AS CEXIGEGUIURG,' ' AS CEXIGEAUTURG,' ' AS CEXIGESENAMB,' ' AS CEXIGEGUIAMB,
' ' AS CEXIGEAUTAMB,EXIGE_SEN_INT,EXIGE_GUI_INT,EXIGE_AUT_INT,EXIGE_SEN_EXT,EXIGE_GUI_EXT,EXIGE_AUT_EXT,
EXIGE_SEN_URG,EXIGE_GUI_URG,EXIGE_AUT_URG,EXIGE_SEN_AMB,EXIGE_GUI_AMB,EXIGE_AUT_AMB,VALIDA
FROM FACONEXP WHERE COD_CON = '014' AND COD_PLA = '01'

select * from faconexp
