SELECT FAFATCAD.COD_MATRICULA, FAUSUCAD.NOME, FAPACCAD.TIPO_PAC, FASETCAD.DESCRICAO, COUNT(*) COUNT_2, 
       SUM(FAFATCAD.VALOR_TOT) SUM_FAFATCAD_VALOR, 
       decode(tipo_pac,'I','Interno') tipo_pac
FROM FAFATCAD FAFATCAD, FAPACCAD FAPACCAD, FAUSUCAD FAUSUCAD, FAFATPRD FAFATPRD, FASETCAD FASETCAD
WHERE (FAPACCAD.COD_PAC = FAFATCAD.COD_PAC (+))
       AND (FAUSUCAD.MATRICULA = FAFATCAD.COD_MATRICULA)
       AND (FAFATPRD.FATURA = FAFATCAD.FATURA)
       AND (FASETCAD.COD_SET = FAFATPRD.COD_SET)
       AND ((FAFATCAD.DATA_EMISS BETWEEN TO_DATE('2015/05/01','YYYY/MM/DD') AND TO_DATE('2015/05/31','YYYY/MM/DD')))
       and fapaccad.tipo_pac = 'I'
       and fasetcad.descricao like 'POSTO%'
GROUP BY FAFATCAD.COD_MATRICULA, FAUSUCAD.NOME, 
         FAPACCAD.TIPO_PAC, FASETCAD.DESCRICAO
ORDER BY FAPACCAD.TIPO_PAC, FASETCAD.DESCRICAO, 
         5 DESC
