CREATE TABLE ADMWPD.ARQFATPRD (
  FATURA VARCHAR2(6) NOT NULL,
  COD_PAC VARCHAR2(7) NOT NULL,
  COD_SET VARCHAR2(4) NOT NULL,
  COD_PRD VARCHAR2(6) NOT NULL,
  COD_PRO VARCHAR2(6) NOT NULL,
  TIPO_PGTO VARCHAR2(1) NOT NULL
);
-- create index
CREATE INDEX ARQFATPRD ON ARQFATPRD (FATURA,COD_PAC,COD_SET,COD_PRD,COD_PRO,TIPO_PGTO);

-- give privileges
GRANT SELECT,INSERT,UPDATE,DELETE,REFERENCES ON ARQFATPRD TO WPD;
