SELECT MOVDES.SEQUENCIAL_PCT, FA_PRT.NOME_PAC, FA_PAC.COD_PAC, FA_TIP.TIPO_PRD, FA_TIP.PRE_CLASS, FA_PRD.CODIGO, DECODE(MOVDES.SEQUENCIAL_PCT, '',
TRIM(FA_PRD.DESCRICAO), TRIM(FA_PRD.DESCRICAO)||'*') AS DESCRICAO_PRODUTO, FA_MOC.COMANDA, TO_CHAR(FA_MOC.DATA_MOV,'DD/MM/YYYY') as DATA_MOV,
TO_CHAR(FA_MOC.HORA_MOV,'HH24:MI') AS HORA_MOV, MOVDES.VALOR_TOT, MOVDES.VALOR, FA_MOV.QUANT, FA_MOV.TIPO_ATO, FA_MOV.COD_KIT,
MOVDES.DESTINO, MOVDES.DESTINO_COBERTURA, FA_SET.COD_SET, FA_SET.DESCRICAO AS DESCRICAO_SETOR, FA_CON.COD_CON, PLACAD.COD_PLA,
FA_CON.COD_CON||' - '||FA_CON.FANTASIA||' / '||PLACAD.COD_PLA||' - '||PLACAD.NOME_PLANO AS FACONCAD_COD_CON_F, FA_PAC.TIPO_PAC,
DECODE(FA_PAC.TIPO_PAC,'I','INTERNO','A','AMBULATÓRIO','U','URGÊNCIA','E','EXTERNO') DECODE_FAPACCAD_TI, AM_UNI.COD_UNI,
AM_UNI.COD_UNI||' - '||AM_UNI.NOME_UNI AMUNICAD_COD_UNI_A,

(SELECT P.CODIGO || ' - ' || P.DESCRICAO PACO FROM FAMOVDESTINO D, FAMOVPRD MP, FAPRDCAD P
WHERE MP.SEQUENCIAL = D.SEQUENCIAL AND MP.CODIGO = P.CODIGO AND D.SEQUENCIAL = MOVDES.SEQUENCIAL_PCT ) PACOTE

FROM FAMOVCAD FA_MOC, FAMOVPRD FA_MOV, FAMOVDESTINO MOVDES, FAPRDCAD FA_PRD, FACONCAD FA_CON, FAPLACAD PLACAD, FASETCAD FA_SET,
FAPACCAD FA_PAC, FAPRTCAD FA_PRT, AMUNICAD AM_UNI, FATIPCAD FA_TIP

WHERE FA_MOC.COMANDA = FA_MOV.COMANDA
AND FA_MOC.TIPO_COMANDA = FA_MOV.TIPO_COMANDA AND FA_MOV.SEQUENCIAL = MOVDES.SEQUENCIAL AND FA_MOV.CODIGO = FA_PRD.CODIGO
AND FA_CON.COD_CON = FA_PAC.COD_CON AND PLACAD.COD_CON = FA_PAC.COD_CON AND PLACAD.COD_PLA = FA_PAC.COD_PLA
AND FA_SET.COD_SET = FA_MOC.SET_ORI AND FA_PAC.COD_PAC = FA_MOC.COD_PAC AND FA_PRT.COD_PRT = FA_PAC.COD_PRT
AND AM_UNI.COD_UNI = MOVDES.COD_UNI_COBRANCA AND FA_TIP.TIPO_PRD = FA_PRD.TIPO_PRD /*AND MOVDES.DESTINO_COBERTURA <> 'H'*/
AND FA_TIP.PRE_CLASS <> 'KIT'
AND MOVDES.DESTINO = 'H' --AND MOVDES.SEQUENCIAL_PCT IS NULL
AND FA_MOC.DATA_MOV >= TO_DATE('01/01/2017','DD/MM/YYYY')
AND FA_MOC.DATA_MOV <= TO_DATE('31/01/2017','DD/MM/YYYY')
and fa_pac.cod_pac = 'N138286'
ORDER BY 25, 24, 23, 3, 1, 2, 6
