SELECT FACONCAD.FANTASIA, FAPRDCAD.DESCRICAO, 
       COUNT(*) COUNT_2
FROM FACONCAD FACONCAD, FAPACCAD FAPACCAD
     , FAMOVCAD FAMOVCAD, FAMOVPRD FAMOVPRD
     , FAPRDCAD FAPRDCAD, FATIPCAD FATIPCAD
WHERE (FAPACCAD.COD_CON = FACONCAD.COD_CON) AND 
      (FAMOVCAD.COD_PAC = FAPACCAD.COD_PAC) AND 
      (FAMOVPRD.COMANDA = FAMOVCAD.COMANDA)
       AND (FAMOVPRD.TIPO_COMANDA = FAMOVCAD.TIPO_COMANDA)
       AND (FAPRDCAD.CODIGO = FAMOVPRD.CODIGO)
       AND (FATIPCAD.TIPO_PRD = FAPRDCAD.TIPO_PRD)
       AND (
      ( FATIPCAD.PRE_CLASS IN ('HON','EXA') )
       AND ( FAMOVCAD.DATA_MOV BETWEEN TO_DATE('2011/01/01','YYYY/MM/DD') AND TO_DATE('2011/01/31','YYYY/MM/DD') )
       AND ( FAMOVCAD.SET_ORI = '0124' )
       AND ( FAPRDCAD.TIPO_PRD <> 'CON' )
       AND ( FAPRDCAD.DESCRICAO NOT LIKE 'VISITA%' )
       AND ( FAPRDCAD.DESCRICAO NOT LIKE 'PLANTAO%' )
       AND ( FAMOVPRD.TIPO_ATO NOT IN ('02','03','04','05','06') )
      )
GROUP BY FACONCAD.FANTASIA, FAPRDCAD.DESCRICAO
ORDER BY FACONCAD.FANTASIA, FAPRDCAD.DESCRICAO
