SELECT DISTINCT FAFATCAD.FATURA, FAFATCAD.DATA_EMISS, FAPRTCAD.NOME_PAC, FAPACCAD.COD_PAC, FAFATCAD.VALOR_TOT
FROM FAFATPRD,FAPRDCAD,FATIPCAD,FAPACCAD,FAFATCAD,FASETCAD,FACONCAD,FAPRTCAD,FAPRGCAD,ESGCNCAD, FAPACCOM
WHERE FAFATPRD.COD_PRD  = FAPRDCAD.CODIGO AND FAPRDCAD.TIPO_PRD = FATIPCAD.TIPO_PRD AND FAFATCAD.FATURA = FAFATPRD.FATURA
AND FAFATPRD.COD_PAC  = FAPACCAD.COD_PAC AND FAFATCAD.COD_CON  = FACONCAD.COD_CON AND FAPACCAD.COD_PRT  = FAPRTCAD.COD_PRT
AND FASETCAD.COD_SET  = FAFATPRD.COD_SET AND FAPRDCAD.COD_GRU  = FAPRGCAD.COD_PRG(+) AND FAPRDCAD.COD_GCN  = ESGCNCAD.COD_GCN(+)
AND FAPACCAD.COD_PAC = FAPACCOM.COD_PAC
AND FAFATCAD.DATA_EMISS >= '01/01/2012'  AND FAFATCAD.DATA_EMISS <= '31/01/2012'
AND FAFATPRD.COD_SET = '0124'
GROUP BY FAFATCAD.FATURA, FAFATCAD.DATA_EMISS, FAPRTCAD.NOME_PAC, FAPACCAD.COD_PAC, FAFATCAD.VALOR_TOT
