SELECT FAPROCAD.NOME_PRO, COUNT(*) COUNT_2, to_char(FAPACCAD.DATA_ENT,'MMYYYY')
FROM FAPACCAD FAPACCAD, FAPACCOM FAPACCOM
     , FAPROCAD FAPROCAD
WHERE (FAPACCOM.COD_PAC = FAPACCAD.COD_PAC) AND 
      (FAPROCAD.COD_PRO = FAPACCAD.COD_PRO) AND (
      ( FAPACCAD.DATA_ENT BETWEEN TO_DATE('2014/01/01','YYYY/MM/DD') AND TO_DATE('2014/12/31','YYYY/MM/DD') )
       AND ( FAPACCAD.TIPO_PAC = 'I' )
       AND ( FAPACCAD.COD_ALA <> 'HMDA' ))
GROUP BY FAPROCAD.NOME_PRO, to_char(FAPACCAD.DATA_ENT,'MMYYYY')
ORDER BY 1, FAPROCAD.NOME_PRO
