SELECT FAESPCAD.COD_ESP, FAESPCAD.DESCRICAO, 
       COUNT(*) COUNT_2
FROM FAPACCAD FAPACCAD, FAESPCAD FAESPCAD, fapaccom fapaccom
WHERE (FAESPCAD.COD_ESP = FAPACCAD.COD_ESP) AND 
fapaccad.cod_pac = fapaccom.cod_pac and
(
      ( FAPACCAD.DATA_ENT BETWEEN TO_DATE('2013/01/01','YYYY/MM/DD') AND TO_DATE('2013/01/31','YYYY/MM/DD') )
       AND ( FAPACCOM.COD_PCN = 'PS' )       AND ( FAPACCAD.TIPO_PAC = 'I' ))
GROUP BY FAESPCAD.COD_ESP, FAESPCAD.DESCRICAO
ORDER BY 3 DESC, FAESPCAD.DESCRICAO


SELECT FAPACCAD.COD_PAC, FAPRTCAD.NOME_PAC, 
       FAPACCAD.TIPO_PAC, FAPACCOM.COD_PCN, 
       FAPACCAD.DATA_ENT
FROM FAPACCAD FAPACCAD, FAPACCOM FAPACCOM
     , FAPRTCAD FAPRTCAD
WHERE (FAPACCOM.COD_PAC = FAPACCAD.COD_PAC) AND 
      (FAPRTCAD.COD_PRT = FAPACCAD.COD_PRT) AND (
      ( FAPACCAD.DATA_ENT BETWEEN TO_DATE('2013/01/01','YYYY/MM/DD') AND TO_DATE('2013/01/31','YYYY/MM/DD') )
       AND ( FAPACCOM.COD_PCN = 'PS' )
       AND ( FAPACCAD.TIPO_PAC = 'I' ))
ORDER BY FAPRTCAD.NOME_PAC, FAPACCAD.DATA_ENT
