update MGGLO.GLO_LOGACESSOSISTEMA
set USU_DT_LOGOUT = SYSDATE
where USU_DT_LOGOUT is null
and usu_st_enderecoip in (
SELECT DISTINCT USU_ST_ENDERECOIP FROM MGGLO.GLO_LOGACESSOSISTEMA
WHERE USU_DT_LOGOUT IS NULL
AND USU_ST_ENDERECOIP NOT IN (SELECT USU_ST_ENDERECOIP
FROM MGGLO.GLO_LOGACESSOSISTEMA LOG, MGGLO.GLO_GRUPO_USUARIO USU
WHERE USU.GRU_IN_CODIGO = LOG.USU_IN_CODIGO AND USU_DT_LOGIN = TRUNC(SYSDATE) AND USU_DT_LOGOUT IS NULL
AND ((SYSDATE - USU_DT_ULTACESSO) * 1440) < 60
GROUP BY USU_IN_CODIGO, GRU_ST_NOME, USU_ST_ENDERECOIP)
AND USU_ST_ENDERECOIP NOT IN ('172.20.2.74','172.20.20.12','172.29.2.53'))
