SELECT FIL.FIL_IN_CODIGO, COL.COL_IN_CODIGO, PES.PES_ST_NOME, ADM.ADM_DT_ADMISSAO, 
       PKG_RH_CALCULO.F_EmAfastamento(COL.COL_IN_CODIGO,'31/05/2013') AS EM_AFAST,
       PKG_RH_CALCULO.F_EmAdmissao(COL.COL_IN_CODIGO,'31/05/2013') AS EM_ADM,
       PKG_RH_CALCULO.F_EmFerias(COL.COL_IN_CODIGO,'31/05/2013') AS EM_FERIAS,
       PKG_RH_CALCULO.F_EmRescisao(COL.COL_IN_CODIGO,'31/05/2013') AS EM_RESCISAO,
       (SELECT RES_DT_RESCISAO FROM RH_RESCISAO WHERE COL_IN_CODIGO = COL.COL_IN_CODIGO) AS DT_RESCISAO,
       COL.COL_RE_SALDO, COL.COL_IN_SALDO13
FROM RH_COLABORADOR COL, RH_PESSOA PES, RH_ADMISSAO ADM, RH_HIST_ORGANOGRAMA FIL
WHERE COL.COL_IN_CODIGO = ADM.COL_IN_CODIGO
AND   COL.PES_IN_CODIGO = PES.PES_IN_CODIGO
AND   COL.COL_IN_CODIGO = FIL.COL_IN_CODIGO
AND   FIL.HOR_DT_INICIO = (SELECT MAX(HOR_DT_INICIO)
                           FROM RH_HIST_ORGANOGRAMA
                           WHERE COL_IN_CODIGO = COL.COL_IN_CODIGO)
AND   COL.COL_IN_CODIGO NOT IN (SELECT COL_IN_CODIGO FROM RH_RESCISAO WHERE RES_DT_RESCISAO < '01/05/2013')
ORDER BY 1,3
