SELECT FAPACCAD.LEITO, FALEICAD.POSTO_ENF, FAPACCAD.COD_PAC, FAPACCAD.COD_PRT,FAPRTCAD.NOME_PAC,
TO_CHAR(FAPACCAD.DATA_ENT,'DD/MM/YYYY') DATA_ENT,TO_CHAR(FAPACCAD.HORA_ENT,'HH24:MI') HORA_ENT,
(TRUNC(SYSDATE - FAPACCAD.DATA_ENT)) AS DI 
FROM FAPACCAD, FALEICAD, FAPRTCAD
WHERE FALEICAD.COD_PAC = FAPACCAD.COD_PAC AND
FAPACCAD.LEITO = FALEICAD.LEITO AND FAPACCAD.COD_PRT = FAPRTCAD.COD_PRT
AND FAPACCAD.TIPO_PAC = 'I' and faleicad.leito not like 'P%' and faleicad.leito not like 'U%' and faleicad.leito not like 'R%'
