CREATE TABLE ARQTEMPPLA33191776 (TIPO_APE_EXC VARCHAR2(1),COD_CON VARCHAR2(3),COD_PLA VARCHAR2(2)) 

CREATE TABLE ARQTEMPPRO33191776 (TIPO_APE_EXC VARCHAR2(1),COD_PRO VARCHAR2(6)) 

CREATE TABLE ARQREQDEV33191776 (REQ_DEV     VARCHAR(1), SINAL NUMBER(5))

INSERT INTO ARQREQDEV33191776 VALUES ('R',1)

INSERT INTO ARQREQDEV33191776 VALUES ('D',-1)

SELECT TIPO_APE_EXC, COD_PRO FROM ARQTEMPPRO33191776

SELECT COD_PRO FROM FAPROCAD WHERE COD_PRO = :1
SELECT NOME_PRO FROM FAPROCAD WHERE COD_PRO = :1

insert into arqtemppro33191776 (tipo_ape_exc, cod_pro) values (:1, :2)

SELECT TIPO_PRD, DESCRICAO FROM FATIPCAD 

SELECT FAPROCAD.COD_PRO ,FAPACCAD.COD_CON,FAPACCAD.TIPO_PAC,FAPROCAD.NOME_PRO, COUNT(*) AS QTD_ATE
FROM FAPACCAD, FAPROCAD WHERE FAPROCAD.COD_PRO = FAPACCAD.COD_PRO  AND FAPACCAD.DATA_ENT >= '01/06/2018'
AND FAPACCAD.DATA_ENT <= '30/06/2018'  AND FAPACCAD.COD_PRO  IN ('000124')  AND FAPACCAD.TIPO_PAC IN ('A')
AND FAPACCAD.COD_UNI IN ('0001') GROUP BY FAPROCAD.COD_PRO,FAPACCAD.COD_CON,FAPACCAD.TIPO_PAC,FAPROCAD.NOME_PRO
ORDER BY FAPROCAD.NOME_PRO 
