SELECT FADOCUMENTOS.DOCUMENTO, PROTOCOLO.COD_PROTOCOLO, FADOCUMENTOS.COD_PAC COD_PACIENTE,
       COD_SETOR_REMESA, PROTOCOLO.COD_SETOR_DESTINO, DAT_REMESSA DAT_REMESSA2,
       PROTOCOLO.DAT_REMESSA,
--       TO_CHAR(PROTOCOLO.DAT_REMESSA,'D/M/Y H:M') DAT_REMESSA,
       PROTOCOLO.NOM_USUARIO_REMET, FASETCAD.*, FAUSUCAD.*
  FROM PROTOCOLO,FASETCAD,FAUSUCAD,ITEM_PROTOCOLO, FADOCUMENTOS
 WHERE 1 = 1
--   AND protocolo.cod_protocolo = '0000077'
   AND PROTOCOLO.NOM_USUARIO_REMET = FAUSUCAD.MATRICULA
   AND PROTOCOLO.COD_SETOR_REMESA  = FASETCAD.COD_SET
   AND ITEM_PROTOCOLO.COD_PROTOCOLO = PROTOCOLO.COD_PROTOCOLO
   AND ITEM_PROTOCOLO.SEQUENCIAL = FADOCUMENTOS.SEQUENCIAL
ORDER BY PROTOCOLO.COD_PROTOCOLO
