SELECT decode(FAPACCAD.TIPO_PAC,'A','AMBULATORIO','E','EXTERNO','I','INTERNO','U','URGENCIA') TIPO_PAC, FACONCAD.FANTASIA,
FAREMCAD.DATA_EMISS, FAREMCAD.REMESSA, FAFATCAD.FATURA, FAPACCAD.COD_PAC, FAPRTCAD.NOME_PAC, FAPACCAD.MATRICULA,
FAPACCAD.DATA_ENT, FAPACCAD.DATA_ALTA, FAPACCAD.NUM_GUIA, FAFATCAD.VALOR_GUIA
FROM FAPACCAD FAPACCAD, FAPRTCAD FAPRTCAD
     , FACONCAD FACONCAD, FAFATCAD FAFATCAD
     , FAREMCAD FAREMCAD
WHERE (FAPRTCAD.COD_PRT = FAPACCAD.COD_PRT) AND 
      (FACONCAD.COD_CON = FAPACCAD.COD_CON) AND 
      (FAFATCAD.COD_PAC = FAPACCAD.COD_PAC) AND 
      (FAREMCAD.REMESSA = FAFATCAD.REMESSA) AND (
      ( FACONCAD.COD_CON <> '001,002' )
       AND ( FAREMCAD.OBSERVACAO LIKE 'COMERCIAL%' )
      )
ORDER BY FAPACCAD.TIPO_PAC, FACONCAD.FANTASIA, 
         FAREMCAD.DATA_EMISS, FAREMCAD.REMESSA, FAPRTCAD.NOME_PAC
