(SELECT SUM(SUM(FAFATPRD.VALOR_TOT)+SUM(FAFATPRD.VALOR_TAXA)) FROM FAFATPRD,FAPRDCAD,FATIPCAD,FAPACCAD,
FAFATCAD,FASETCAD,FACONCAD,FAREMCAD,FAPRTCAD,FAPRGCAD,ESGCNCAD WHERE FAFATPRD.COD_PRD = FAPRDCAD.CODIGO
AND FAPRDCAD.TIPO_PRD = FATIPCAD.TIPO_PRD AND FAFATCAD.FATURA   = FAFATPRD.FATURA AND FAFATPRD.COD_PAC  = FAPACCAD.COD_PAC
AND FAFATCAD.COD_CON  = FACONCAD.COD_CON AND FAPACCAD.COD_PRT  = FAPRTCAD.COD_PRT AND FASETCAD.COD_SET  = FAFATPRD.COD_SET
AND FAPRDCAD.COD_GRU  = FAPRGCAD.COD_PRG(+) AND FAPRDCAD.COD_GCN  = ESGCNCAD.COD_GCN(+) AND FAFATCAD.REMESSA = FAREMCAD.REMESSA
AND FAfatcad.Data_Emiss >= '01/07/2016' AND FAfatcad.Data_Emiss <= '31/07/2016'  AND FAFATPRD.TIPO_PGTO IN ('D','H','R')
AND FAFATPRD.COD_SET  IN ('0133') AND FAPACCAD.TIP_ATEND IN ('L','M','I','P','S') AND FAPACCAD.TIPO_PAC IN ('I')
AND FAFATCAD.COD_UNI IN ('0001')
GROUP BY FAFATPRD.FATURA)
/
(select sum(quant) from fafatprd where cod_set = '0133' and fatura in (select fatura from fafatcad where data_emiss
between '01/07/2016' and '31/07/2016')
and cod_prd in (select codigo from faprdcad where tipo_prd = 'DIA'))
