SELECT DISTINCT FAPRDCAD.CODIGO Codigo,(FAPRDCAD.DESCRICAO) Produto,
       EXTRACT(MONTH FROM FAFATCAD.DATA_EMISS) ||'/'|| EXTRACT (YEAR FROM FAFATCAD.DATA_EMISS) MesAno,
       SUM(FAFATPRD.QUANT) Qtd,
       SUM(FAFATPRD.VALOR_TOT) Valor,
       DECODE (FAPRDCAD.COD_ABRAMGE,'1','N','0','S') Impostos  
FROM   FAFATCAD, FAFATPRD, FAPRDCAD
WHERE  FAFATCAD.FATURA = FAFATPRD.FATURA
AND    FAFATPRD.COD_PRD = FAPRDCAD.CODIGO 
AND    EXTRACT (YEAR FROM FAFATCAD.DATA_EMISS) BETWEEN 2016 AND 2016
AND    EXTRACT (MONTH FROM FAFATCAD.DATA_EMISS) BETWEEN 04 AND 04
AND    EXTRACT (DAY FROM FAFATCAD.DATA_EMISS) BETWEEN 01 AND 30
AND    FAPRDCAD.TIPO_PRD = 'MED'
AND    FAPRDCAD.COD_ABRAMGE = '0'--1 é Não isento. 0 é isento.
GROUP BY(FAPRDCAD.CODIGO,FAPRDCAD.DESCRICAO,EXTRACT(MONTH FROM FAFATCAD.DATA_EMISS) ||'/'||
EXTRACT (YEAR FROM FAFATCAD.DATA_EMISS),FAPRDCAD.COD_ABRAMGE);
