SELECT A.NU_SENHA,A.DH_RETIRADA,B.DS_FILA,B.SN_ZERA_NOVO_DIA 
FROM TB_SEL_SENHA_FILA A
JOIN  TB_TRIAGEM_FILA B
ON (B.PK_TRIFIL=A.FK_TRIFIL)
WHERE TO_CHAR(DH_RETIRADA,'dd/mm/yyyy')='15/08/2013'
AND DS_FILA = 'NORMAL - PS'
