SELECT REL_IMP_ONLINE.CONDICAO, 
       REL_IMP_ONLINE.ITEM_ID, 
       REL_IMP_ONLINE.CAMPO_RETORNO, 
       REL_EXP_ITEM.NOME_ITEM, 
       REL_IMP_ONLINE.NUM_COPIAS 
  FROM REL_IMP_ONLINE, REL_EXP_ITEM 
 WHERE REL_IMP_ONLINE.ITEM_ID = REL_EXP_ITEM.ITEM_ID 
   AND SISTEMA = 'VIS'
   AND COD_MOD = 'RCVIS'
   AND ( COD_FUN = 'EVS' OR COD_FUN IS NULL OR COD_FUN = ' ' )
   AND ( COD_GRUPO = 'TI' OR COD_GRUPO IS NULL OR COD_GRUPO = ' ' ) 
