SELECT count(*)
FROM VISITA a, VISITA_VISITANTE b, VISITANTE c, TIPO_VISITA d
WHERE b.COD_VISITA = a.COD_VISITA
AND c.COD_VISITANTE = b.COD_VISITANTE
AND d.COD_TIPO_VISITA = a.COD_TIPO_VISITA
and a.data_ini between '01/07/2015' and '31/07/2015'
