CREATE USER ESOCIAL IDENTIFIED BY ESOCIAL
DEFAULT TABLESPACE VETORH_ESOCIAL
TEMPORARY TABLESPACE TMPSENIOR_GROUP
PROFILE DEFAULT
QUOTA UNLIMITED ON VETORH_ESOCIAL;

grant connect to esocial;
grant all privileges to esocial;

GRANT ALTER SESSION TO esocial;

GRANT SELECT ANY DICTIONARY TO esocial;

GRANT CONNECT TO esocial;

GRANT RESOURCE TO esocial;

GRANT CREATE VIEW TO esocial;