drop role role_mega;
CREATE ROLE ROLE_MEGA IDENTIFIED BY MEGA;
GRANT CONNECT TO ROLE_MEGA;
GRANT RESOURCE TO ROLE_MEGA;
GRANT ALTER USER TO ROLE_MEGA;
GRANT CREATE VIEW TO ROLE_MEGA;
GRANT CREATE ANY CONTEXT to ROLE_MEGA;
GRANT CREATE ANY SYNONYM TO ROLE_MEGA;
grant create snapshot to role_mega;
grant debug connect session to role_mega;

SELECT * FROM V$SESSION_LONGOPS WHERE TOTALWORK > SOFAR;