--Bytes livres
SELECT tablespace_name, round((sum(bytes)/sum(maxbytes))*100,2) max_bytes FROM DBA_TEMP_FILES
group by tablespace_name
order by (sum(bytes)/sum(maxbytes)) desc;

select * from dba_temp_files

--CREATE TEMPORARY TABLESPACE tmpagfa TEMPFILE 'H:\ORADATA\PROD\DATAFILE\01TMPAGFA.TMP' SIZE 100m AUTOEXTEND ON NEXT 100m MAXSIZE 16G;
EXTENT MANAGEMENT LOCAL;
ALTER TEMPORARY TABLESPACE CTODADOS ADD TEMPFILE 'H:\oradata\HOMOL\DATAFILE\TEMP01.TMP' SIZE 100M AUTOEXTEND ON NEXT 100M MAXSIZE 4G;
--alter tablespace temp3 tablespace group TMP1_GROUP;

select 	USERNAME,	CREATED, PROFILE,	DEFAULT_TABLESPACE,	TEMPORARY_TABLESPACE from dba_users where TEMPORARY_TABLESPACE = 'TMPAGFA' order by 4

alter user admcto temporary tablespace tmpagfa;

ALTER DATABASE TEMPFILE 'H:\ORADATA\PROD\DATAFILE\01_TEMPAGFA.TMP' OFFLINE;
ALTER DATABASE TEMPFILE 'H:\ORADATA\HOMOL\DATAFILE\O1_TEMP1.TMP' DROP INCLUDING DATAFILES;
ALTER DATABASE TEMPFILE 'H:\oradata\PROD\DATAFILE\01_TEMPAGFA.TMP' DROP INCLUDING DATAFILES;

ALTER TABLESPACE TEMPMEGA ADD TEMPFILE 'H:\ORADATA\PROD\DATAFILE\01_TEMPMEGA.TMP' SIZE 100M AUTOEXTEND ON;


/*select * from dba_tablespace_groups;
ALTER TABLESPACE 01_TEMPMEGA2.TMP TABLESPACE GROUP '';
ALTER TABLESPACE agfatemp3 TABLESPACE GROUP '';
drop tablespace TMPWPD_GROUP including contents and datafiles;
*/
