--Consumo faturado:
SELECT (SUM(SUM(FAFATPRD.VALOR_TOT)) + SUM(SUM(FAFATPRD.VALOR_TAXA))) TOTAL_FATURADO
FROM FAFATPRD,FAPRDCAD,FATIPCAD,FAPACCAD,FAFATCAD,FASETCAD,FACONCAD,FAPRTCAD,FAPRGCAD,ESGCNCAD
WHERE FAFATPRD.COD_PRD  = FAPRDCAD.CODIGO AND FAPRDCAD.TIPO_PRD = FATIPCAD.TIPO_PRD AND FAFATCAD.FATURA = FAFATPRD.FATURA
AND FAFATPRD.COD_PAC  = FAPACCAD.COD_PAC AND FAFATCAD.COD_CON  = FACONCAD.COD_CON AND FAPACCAD.COD_PRT  = FAPRTCAD.COD_PRT
AND FASETCAD.COD_SET  = FAFATPRD.COD_SET AND FAPRDCAD.COD_GRU  = FAPRGCAD.COD_PRG(+) AND FAPRDCAD.COD_GCN  = ESGCNCAD.COD_GCN(+) 
AND FAFATCAD.DATA_EMISS >= '01/10/2012'  AND FAFATCAD.DATA_EMISS <= '31/10/2012'
and fafatprd.cod_set = '0376'--  ('0137','0311','0344','0346','0347','0348','0349','0351','0374','0375','0376','0377','0378','0406')
GROUP BY FAFATPRD.FATURA

SELECT (SUM(SUM(FAFATPRD.VALOR_TOT)) + SUM(SUM(FAFATPRD.VALOR_TAXA))) TOTAL_FATURADO
FROM FAFATPRD,FAPRDCAD,FATIPCAD,FAPACCAD,FAFATCAD,FASETCAD,FACONCAD,FAPRTCAD,FAPRGCAD,ESGCNCAD
WHERE FAFATPRD.COD_PRD  = FAPRDCAD.CODIGO AND FAPRDCAD.TIPO_PRD = FATIPCAD.TIPO_PRD AND FAFATCAD.FATURA = FAFATPRD.FATURA
AND FAFATPRD.COD_PAC  = FAPACCAD.COD_PAC AND FAFATCAD.COD_CON  = FACONCAD.COD_CON AND FAPACCAD.COD_PRT  = FAPRTCAD.COD_PRT
AND FASETCAD.COD_SET  = FAFATPRD.COD_SET AND FAPRDCAD.COD_GRU  = FAPRGCAD.COD_PRG(+) AND FAPRDCAD.COD_GCN  = ESGCNCAD.COD_GCN(+) 
AND FAFATCAD.DATA_EMISS >= '01/10/2012'  AND FAFATCAD.DATA_EMISS <= '31/10/2012'  AND FAFATPRD.TIPO_PGTO IN ('D','H','R')
AND FAPACCAD.TIP_ATEND IN ('L','M','I','P') AND FAPACCAD.TIPO_PAC IN ('I','E','U','A') AND FAFATCAD.COD_UNI IN ('0001')
and fafatprd.cod_set in ('0137','0311','0344','0346','0347','0348','0349','0351','0374','0375','0376','0377','0378','0406')
GROUP BY FAFATPRD.FATURA
