--Principal
SELECT c.fantasia, a.usu_recepcao, COUNT(*) * 1.0 AS QTD FROM IMMOVCAD a, fapaccad b, faconcad c
WHERE a.cod_pac = b.cod_pac and b.cod_con = c.cod_con 
 AND a.DATA_MOV >= TO_DATE('01/09/2015','DD/MM/YYYY')  AND a.DATA_MOV <= TO_DATE('01/09/2015','DD/MM/YYYY') 
GROUP BY c.fantasia, a.USU_RECEPCAO
order by 2,1


CREATE TABLE ATENDRECEPTMP23867059 (NOME_RECEP VARCHAR2(40), QUANT_SEDEX NUMBER(10), PERC_SEDEX      NUMBER(5,2),   QUANT_DOM       NUMBER(10),    PERC_DOM        NUMBER(5,2),   QUANT_RECEP     NUMBER(10),    PERC_RECEP      NUMBER(5,2),   TOTAL_GERAL     NUMBER(10))

SELECT COUNT(*) * 1.0 AS QTD FROM IMMOVCAD WHERE IMMOVCAD.COD_UNI IN ('0001') 
AND IMMOVCAD.DATA_MOV >= TO_DATE('01/09/2015','DD/MM/YYYY') AND IMMOVCAD.DATA_MOV <= TO_DATE('01/09/2015','DD/MM/YYYY')
 
UPDATE ATENDRECEPTMP23867059 SET TOTAL_GERAL= :1 WHERE NOME_RECEP= :2
  
SELECT DISTINCT DATA_MOV FROM IMMOVCAD WHERE IMMOVCAD.COD_UNI IN ('0001')
 AND IMMOVCAD.DATA_MOV >= TO_DATE('01/09/2015','DD/MM/YYYY') AND IMMOVCAD.DATA_MOV <= TO_DATE('01/09/2015','DD/MM/YYYY')
 
SELECT USU_RECEPCAO, TIPO_ENTREGA_EXA, COUNT(*) * 1.0 AS QTD FROM IMMOVCAD WHERE IMMOVCAD.COD_UNI IN ('0001') 
 AND IMMOVCAD.DATA_MOV >= TO_DATE('01/09/2015','DD/MM/YYYY')  AND IMMOVCAD.DATA_MOV <= TO_DATE('01/09/2015','DD/MM/YYYY') 
GROUP BY USU_RECEPCAO, TIPO_ENTREGA_EXA

SELECT * FROM ATENDRECEPTMP23867059 WHERE NOME_RECEP= :1

INSERT INTO ATENDRECEPTMP23867059 (NOME_RECEP,QUANT_RECEP) VALUES (:1,:2)

SELECT
  FAPACCAD.COD_PAC,
  FAPRTCAD.NOME_PAC,
  FAPRTCAD.FONE_RES,
  IMMOVCAD.DATA_MOV,
  IMMOVCAD.HORA_MOV,
  IMMOVCAD.TIPO_ENTREGA_EXA
FROM
  IMMOVCAD,
  FAPACCAD,
  FAPRTCAD
WHERE
 (IMMOVCAD.USU_RECEPCAO  = ?)
  AND
 (IMMOVCAD.DATA_MOV     >= ?)
  AND
 (IMMOVCAD.DATA_MOV     <= ?)
  AND
 (IMMOVCAD.COD_PAC       = FAPACCAD.COD_PAC)
  AND
 (FAPACCAD.COD_PRT       = FAPRTCAD.COD_PRT)
AND IMMOVCAD.cod_uni IN ('0001') 
ORDER BY
  IMMOVCAD.TIPO_ENTREGA_EXA,
  FAPACCAD.COD_PAC
