TRUNCATE TABLE TITCR_TCR;
TRUNCATE TABLE TITCRGR_RGR;
TRUNCATE TABLE TITCRFC_RFC;
TRUNCATE TABLE FATURAS_FAT;
TRUNCATE TABLE ITFATURA_IFAT;
TRUNCATE TABLE ITFATURAHOSP_IFH;
TRUNCATE TABLE MOTGLOSACLA_MGC;
TRUNCATE TABLE MOTGLOSACLAH_MGCH;
--
DELETE FROM BAIXALAMINA_BXL;
DELETE FROM SELECAOBAIXA_SBX;
DELETE FROM CLASSIFPROCLAMINA_CPL;
DELETE FROM SELECAOCLASSIF_SCL;
--
COMMIT;
--