SET LINESIZE 1000 PAGESIZE 1000 verify off;

PROMPT **********************************************************************
PROMPT **** ESTE COMANDO IRÁ SALVAR UM ARQUIVO NO DIRETÓRIO "C" DA MÁQUINA  * 
PROMPT **** CHAMADO ARQUIVO_MOV_ITEM.TXT                                    *
PROMPT **********************************************************************
ACCEPT EMPRESA PROMPT 'ENTRE COM O CÓDIGO DA EMPRESA: '
ACCEPT ESTOQUE PROMPT 'ENTRE COM O CÓDIGO DO ESTOQUE: '
ACCEPT ALMOX PROMPT 'ENTRE COM O CÓDIGO DO ALMOXARIFADO (CASO QUEIRA TODOS USE "%"): '
ACCEPT DATA PROMPT 'ENTRE COM O MES E ANO (EX.: 052004): '


SPOOL C:\ARQUIVO_MOV_ITEM.TXT;

SELECT DISTINCT MOV_ITEM CODIGO
       , SUM(ENT) QUANT_ENT
       , SUM(SAI) QUANT_SAI
FROM
(
SELECT
       MOV_ITEM
       ,NVL(SUM(MOV_QTD),0) ENT
       ,0 SAI
  FROM MOVIMENTO_MOV
 WHERE MOV_TIPO = 'E'
   AND MOV_CDEMPRESA = '&EMPRESA'
   AND MOV_TPESTOQUE = '&ESTOQUE'
   AND MOV_ALMOXARIFADO LIKE '&ALMOX'
   AND TO_CHAR(MOV_DATA,'MMYYYY') = '&DATA'
 GROUP BY MOV_ITEM
UNION ALL
SELECT
       MOV_ITEM
       ,0 ENT
       ,NVL(SUM(MOV_QTD),0) SAI
  FROM MOVIMENTO_MOV
 WHERE MOV_TIPO = 'S'
   AND MOV_CDEMPRESA = '&EMPRESA'
   AND MOV_TPESTOQUE = '&ESTOQUE'
   AND MOV_ALMOXARIFADO LIKE '&ALMOX'
   AND TO_CHAR(MOV_DATA,'MMYYYY') = '&DATA'
 GROUP BY MOV_ITEM
) 
GROUP BY MOV_ITEM
/

SPOOL OFF;