SELECT OWNER,COUNT(*)
FROM ALL_OBJECTS
WHERE OBJECT_TYPE='TABLE'
AND owner not in ('SYS','MDSYS','XDB','OE','SCOTT','OLAPSYS','HR','WKSYS','ODM','WMSYS','QS','QS_CBADM','QS_CS','QS_ES','QS_OS','QS_WS','RMAN','SYSTEM','CTXSYS','ODM_MTR','ORDSYS','OUTLN','PM','SH')
GROUP BY OWNER 
ORDER BY OWNER;