SET ECHO OFF
SET PAGESIZE 37
SET FEEDBACK OFF
SET LINESIZE 78

TTITLE 'TESTE DE RELATÓRIO'
--BTITLE 'SEGUNDO TITULO'

COL A FORMAT A15   HEADING 'CODIGO' TEMP
COL B FORMAT A30   HEADING 'NOME' TEMP
COL C FORMAT A18   HEADING 'CGC' TEMP

SELECT
 FOR_CODIGO A,
 FOR_NOME B,
 FOR_CGC C
FROM FORNEC_FOR
/
TTITLE OFF
--BTITLE OFF
SET FEEDBACK ON
SET PAGES 24
CLEAR BREAKS
CLEAR COMPUTES