SELECT ITM_SQINTEGRACAO AS SQINTEGRACAO, ITM_TPINTEGRACAO FROM TITCP_TCP, INTMODTCP_IMP, INTEGMODULOS_ITM   
WHERE TCP_CDFOR = '14722938000120' AND ( TCP_NOTITULO = 'E00000014324' OR TCP_NOTITPARC   = 'E00000014324'
OR TCP_NOTITPARCOR = 'E00000014324') AND IMP_CDFOR = TCP_CDFOR AND IMP_NOTITULO = TCP_NOTITULO AND ITM_SQINTEGRACAO = IMP_SQINTEGRACAO
AND ITM_TPINTEGRACAO NOT IN (9, 12, 14)

SELECT INTEGMODULOS_ITM.*, TITCP_TCP.*, CASE WHEN ITM_TPINTEGRACAO IN(9, 12, 14) THEN (SELECT IMP_SQINTEGRACAO 
FROM INTMODTCP_IMP, INTEGMODULOS_ITM WHERE IMP_CDFOR = TCP_CDFOR AND IMP_NOTITULO = TCP_NOTITULO
AND IMP_SQINTEGRACAO = ITM_SQINTEGRACAO AND ITM_TPINTEGRACAO NOT IN (9, 12, 14)) ELSE ITM_SQINTEGRACAO END AS SQINTEGRACAO 
FROM INTMODTCP_IMP, INTEGMODULOS_ITM, TITCP_TCP WHERE ITM_SQINTEGRACAO = 50770 AND IMP_SQINTEGRACAO = ITM_SQINTEGRACAO
AND IMP_CDFOR = TCP_CDFOR AND IMP_NOTITULO = TCP_NOTITULO

SELECT * FROM TITCP_TCP WHERE TCP_CDFOR = '14722938000120' AND TCP_NOTITULO = 'E00000014324'